import {readdir,readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

export function validateBatches(batches){
 const schedule={};
 const text=(value,max,field)=>{
  if(typeof value!=='string'||!value.trim()||value.length>max||/[<>"\x00-\x1f]/.test(value))throw Error(`Invalid ${field}: use plain text up to ${max} characters, without HTML or double quotes.`);
 };
 for(const {name,data} of batches){
  if(data.schemaVersion!==1||!Array.isArray(data.puzzles)||!data.puzzles.length)throw Error(`${name}: expected schemaVersion 1 and a nonempty puzzles array.`);
  for(const puzzle of data.puzzles){
   const {date,events}=puzzle;
   if(typeof date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date)throw Error(`${name}: invalid UTC date ${date}.`);
   if(Object.hasOwn(schedule,date))throw Error(`${name}: duplicate date ${date}; existing puzzles cannot be replaced by another batch.`);
   if(!Array.isArray(events)||events.length!==5)throw Error(`${date}: exactly five events are required.`);
   const ids=new Set(),years=new Set();
   for(const e of events){
    if(!e||typeof e.id!=='string'||!/^[a-z][a-z0-9-]{0,39}$/.test(e.id)||ids.has(e.id))throw Error(`${date}: invalid or duplicate event ID.`);
    if(!Number.isInteger(e.year)||e.year<1||e.year>new Date(date).getUTCFullYear()||years.has(e.year))throw Error(`${date}: use five distinct CE years, no future events.`);
    text(e.title,110,'title');text(e.label,38,'mobile label');text(e.category,18,'category');text(e.fact,260,'fact');
    let url;try{url=new URL(e.source);}catch{throw Error(`${date}: invalid source URL.`);}
    if(url.origin!=='https://en.wikipedia.org'||!url.pathname.startsWith('/wiki/')||url.pathname.length<=6||url.search||url.hash||url.username||url.password||/[<>"\s]/.test(e.source))throw Error(`${date}: source must be a direct HTTPS English Wikipedia article.`);
    ids.add(e.id);years.add(e.year);
   }
   // Whitelist content fields so extra editorial notes never become public game data.
   schedule[date]=events.map(({id,year,title,label,category,fact,source})=>({id,year,title,label,category,fact,source}));
  }
 }
 return Object.fromEntries(Object.entries(schedule).sort(([a],[b])=>a.localeCompare(b)));
}
export async function loadSchedule(){
 const folder=new URL('../content/batches/',import.meta.url);
 const names=(await readdir(folder)).filter(n=>n.endsWith('.json')).sort();
 if(!names.length)throw Error('No puzzle batches found.');
 const batches=await Promise.all(names.map(async name=>({name,data:JSON.parse(await readFile(new URL(name,folder),'utf8'))})));
 return validateBatches(batches);
}
export const renderSchedule=schedule=>'// Generated by npm run puzzles. Edit content/batches/*.json instead.\nexport const DAILY_PUZZLES = '+JSON.stringify(schedule,null,2)+';\n';
async function main(){
 const schedule=await loadSchedule(),output=renderSchedule(schedule),target=new URL('../dist/puzzles.js',import.meta.url);
 if(process.argv.includes('--check')){if(await readFile(target,'utf8')!==output)throw Error('Generated puzzles are stale. Run npm run puzzles.');}
 else await writeFile(target,output);
 const dates=Object.keys(schedule);console.log(`${dates.length} dated puzzles validated: ${dates[0]} through ${dates.at(-1)}.`);
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(e=>{console.error(e.message);process.exitCode=1;});
